### ISSUE TITLE
Fastboot compatibility?

### ISSUE THREAD

**Issue by bcardarella** [crowdcompass/ember-cli-clamp#1]
Great addon!

Have you considered fastboot compatibility? Ideally during fastboot rendering the entire content would be available and not clamped for SEO/crawling purposes.

**Comment by kyleolsondesign** [comment]
Seems like this would be compatible, since it hooks onto the `willInsertElement` and `didInsertElement` lifecycle hooks, which fastboot is designed to ignore:

https://www.ember-fastboot.com/docs/user-guide

> Use didInsertElement for client-side DOM manipulation
> In FastBoot, we do not invoke either didInsertElement or willInsertElement hooks. If your components have any direct DOM manipulation you would do it in those hooks.

**Comment by renaekathleen** [comment]
I haven't personally tested it, but it seems like it should be compatible, since we followed the Fastboot documentation's suggestions! Therefore, closing the issue.
